# Standard CPCB Column Mapping Schema

COLUMN_MAPPING = {
    'station id': 'station_id',
    '_id': 'station_id',
    'state': 'state',
    'city': 'city',
    'station name': 'station_name',
    'timestamp': 'timestamp',
    'last_update': 'timestamp',

    # Pollutants
    'pm2.5 (ug/m3)': 'pm25',
    'pm2.5 (g/m)': 'pm25',
    'pm2.5': 'pm25',
    'pm10 (ug/m3)': 'pm10',
    'pm10 (g/m)': 'pm10',
    'pm10': 'pm10',
    'no (ug/m3)': 'no',
    'no (g/m)': 'no',
    'no': 'no',
    'no2 (ug/m3)': 'no2',
    'no2 (g/m)': 'no2',
    'no2': 'no2',
    'nox (ppb)': 'nox',
    'nox (g/m)': 'nox',
    'nox': 'nox',
    'nh3 (ug/m3)': 'nh3',
    'nh3 (g/m)': 'nh3',
    'nh3': 'nh3',
    'so2 (ug/m3)': 'so2',
    'so2 (g/m)': 'so2',
    'so2': 'so2',
    'co (mg/m3)': 'co',
    'co (g/m)': 'co',
    'co': 'co',
    'ozone (ug/m3)': 'o3',
    'o3 (ug/m3)': 'o3',
    'o3 (g/m)': 'o3',
    'o3': 'o3',

    # Organics
    'benzene (ug/m3)': 'benzene',
    'benzene (g/m)': 'benzene',
    'toluene (ug/m3)': 'toluene',
    'toluene (g/m)': 'toluene',
    'xylene (ug/m3)': 'xylene',
    'xylene (g/m)': 'xylene',
    'o xylene (ug/m3)': 'o_xylene',
    'ethyl benzene (ug/m3)': 'eth_benzene',
    'mp-xylene (ug/m3)': 'mp_xylene',

    # Meteorology
    'at (deg c)': 'temperature',
    'at (c)': 'temperature',
    'at': 'temperature',
    'temp': 'temperature',
    'rh (%)': 'relative_humidity',
    'rh': 'relative_humidity',
    'humidity': 'relative_humidity',
    'ws (m/s)': 'wind_speed',
    'ws': 'wind_speed',
    'wd (deg)': 'wind_direction',
    'wd (degree)': 'wind_direction',
    'wd': 'wind_direction',
    'rf (mm)': 'rainfall',
    'rf': 'rainfall',
    'tot-rf (mm)': 'total_rainfall',
    'tot-rf': 'total_rainfall',
    'sr (w/mt2)': 'solar_radiation',
    'sr (w/m2)': 'solar_radiation',
    'sr': 'solar_radiation',
    'bp (mmHg)': 'pressure',
    'bp (hpa)': 'pressure',
    'bp': 'pressure',
    'vws (m/s)': 'vertical_wind_speed',
    'vws': 'vertical_wind_speed'
}

STANDARDIZED_COLUMNS = [
    'station_id', 'state', 'city', 'station_name', 'timestamp',
    'pm25', 'pm10', 'no', 'no2', 'nox', 'nh3', 'so2', 'co', 'o3',
    'benzene', 'toluene', 'xylene', 'o_xylene', 'eth_benzene', 'mp_xylene',
    'temperature', 'relative_humidity', 'wind_speed', 'wind_direction',
    'rainfall', 'total_rainfall', 'solar_radiation', 'pressure', 'vertical_wind_speed'
]
